TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this
DB += sr620.db
#DB += asynRecord.db

#----------------------------------------------------
# Create and install (or just install)
# Archive files, templates, substitutions like this
#

#----------------------------------------------------
# Create and install (or just install)
# Autosave request files, templates, substitutions like this
#

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE


